### ISSUE TITLE
site-packages tests not running in build script

### ISSUE THREAD

**Issue by mtlynch** [m-lab/collectd-mlab#39]
It doesn't look like the build script is actually running the tests for files under site-packages:

https://travis-ci.org/m-lab/collectd-mlab/builds/125108950
```
+for dir in export monitoring plugin site-packages system/vsys viewer
+coverage run --append --source ./ --omit third_party/docstringchecker/lint.py -m unittest discover -s site-packages -p '*_test.py'

----------------------------------------------------------------------
Ran 0 tests in 0.000s  <<< no tests run

OK
```

**Comment by stephen-soltesz** [comment]
Good catch.

This worked locally because I have uncommitted, empty `__init__.py` in the `mlab` and `mlab/disco` directories.

Should be fixed by https://github.com/m-lab/collectd-mlab/pull/40

**Comment by stephen-soltesz** [comment]
Nuts. This looks like it will be more complicated.

The dependencies `python-netifaces` and `python-netsnmp` are disallowed (not whitelisted) in the current set of travis-ci packages.

https://github.com/travis-ci/apt-package-whitelist#package-approval-process

**Comment by stephen-soltesz** [comment]
This really bugs me because I though the tests were running in travis before.

Similarly, the pip packages for `netifaces` and `netsnmp` cannot build because their dependencies are not whitelisted.

As a workaround, I can add a new directory, `fake-packages` (like site-packages) and add minimal stub versions of netifaces and netsnmp modules, then modify `.travis.yml` so `build` runs with a modified `PYTHONPATH` that includes `fake-packages`.

        PYTHONPATH=$PYTHONPATH:$PWD/fake-packages ./build 

This appears to work.

**Comment by stephen-soltesz** [comment]
See for example:

https://github.com/stephen-soltesz/collectd-mlab/commit/e3aa2e13341571e8e29c1cd567a86fcfb7d6e5b9

**Comment by stephen-soltesz** [comment]
@mtlynch, would you be willing to comment on this thread and the approach illustrated in https://github.com/stephen-soltesz/collectd-mlab/commit/e3aa2e13341571e8e29c1cd567a86fcfb7d6e5b9 ?

I think this is a reasonable way forward.

**Comment by mtlynch** [comment]
Yeah I think it's a reasonable workaround.

**Comment by stephen-soltesz** [comment]
This was resolved by "fake-packages" work around: https://github.com/m-lab/collectd-mlab/pull/41
