### ISSUE TITLE
Add DISCO collection of Pause Frames for flow-control

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/collectd-mlab#62]
The pause frame counters are:

```
EtherLike-MIB::dot3InPauseFrames.{ifIndex}
EtherLike-MIB::dot3OutPauseFrames.{ifIndex}
```

This should be straight forward addition to the models definitions:
  https://github.com/m-lab/collectd-mlab/blob/master/disco/models.yaml

The mib is available on QFX switches. It seems like a standard mib set -- https://tools.ietf.org/html/rfc3635

**Comment by kokosta** [comment]
Done and verified.
